name: .NET

on: [push, pull_request, workflow_dispatch]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Build WaylandSharper
      run: dotnet build src/WaylandSharper

  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Run tests
      run: dotnet test src/WaylandSharp.Tests
